### ISSUE TITLE
MultiRWST

### ISSUE THREAD

**Issue by pthariensflame** [lspitzner/multistate#1]
How about it?

**Comment by lspitzner** [comment]
I can't see any problems with it, should be mostly a compilation from the other transformers. Do you want to implement it? i accept pull requests :-)
If there is need, i can add it to my todo-list, too.

**Comment by pthariensflame** [comment]
No real _need_, just a _want_.  I'm not too familiar with this implementation's internal patterns, so I wanted check if the idea was feasible before starting work on it. :)

**Comment by lspitzner** [comment]
@pthariensflame the latest versions contain a MultiRWST. The hardest part was finding appropriate function names, because eval/exec/run together with multiple values created a nice mess. I hope the new naming scheme i invented makes some sense :-)

will publish the latest version on hackage soon.
