### ISSUE TITLE
Base version

### ISSUE THREAD

**Issue by RuijieYu** [lspitzner/multistate#4]
When I was trying to build multistate it outputs an error saying the version of base should be `base >=4.9 && <4.14`. Currently the base version is at `4.14` so the build fails. Any plan to update?

**Comment by ulidtko** [comment]
@RuijieYu this is rather idiosyncratic Haskell situation. Somehow, the community seems to agree that every update of GHC (e.g. 8.8 → 8.10) must be accompanied by manual bumps of upper dependency bounds onto the `base` package (the GHC stdlib, sort of) — in every single [PVP-compliant](https://pvp.haskell.org) package.

The usual workaround is to clone the package(s) locally, bump the version bound in `.cabal` and install manually from there.

I've put out a tiny PR to hopefully make this update easier to the maintainer.
